opcache.enable=1
opcache.memory_consumption=128
opcache.max_accelerated_files=10000
opcache.revalidate_freq=0
; Con freq=0, PHP nunca revisa si el archivo cambió en disco.
; Para desarrollo: ponlo en 2 (revisa cada 2 segundos).
; Para producción: 0 es perfecto.
opcache.validate_timestamps=1
opcache.revalidate_freq=2