export interface CountryPhoneOption {
  country: string;
  prefix: string;
  departments: string[];
}

export const COUNTRY_PHONE_OPTIONS: CountryPhoneOption[] = [
  {
    country: "Argentina",
    prefix: "+54",
    departments: [
      "Buenos Aires",
      "Catamarca",
      "Chaco",
      "Chubut",
      "Cordoba",
      "Corrientes",
      "Entre Rios",
      "Formosa",
      "Jujuy",
      "La Pampa",
      "La Rioja",
      "Mendoza",
      "Misiones",
      "Neuquen",
      "Rio Negro",
      "Salta",
      "San Juan",
      "San Luis",
      "Santa Cruz",
      "Santa Fe",
      "Santiago del Estero",
      "Tierra del Fuego",
      "Tucuman",
      "Ciudad Autonoma de Buenos Aires",
    ],
  },
  {
    country: "Bolivia",
    prefix: "+591",
    departments: ["Beni", "Chuquisaca", "Cochabamba", "La Paz", "Oruro", "Pando", "Potosi", "Santa Cruz", "Tarija"],
  },
  {
    country: "Brasil",
    prefix: "+55",
    departments: [
      "Acre",
      "Alagoas",
      "Amapa",
      "Amazonas",
      "Bahia",
      "Ceara",
      "Distrito Federal",
      "Espirito Santo",
      "Goias",
      "Maranhao",
      "Mato Grosso",
      "Mato Grosso do Sul",
      "Minas Gerais",
      "Para",
      "Paraiba",
      "Parana",
      "Pernambuco",
      "Piaui",
      "Rio de Janeiro",
      "Rio Grande do Norte",
      "Rio Grande do Sul",
      "Rondonia",
      "Roraima",
      "Santa Catarina",
      "Sao Paulo",
      "Sergipe",
      "Tocantins",
    ],
  },
  {
    country: "Chile",
    prefix: "+56",
    departments: [
      "Arica y Parinacota",
      "Tarapaca",
      "Antofagasta",
      "Atacama",
      "Coquimbo",
      "Valparaiso",
      "Metropolitana de Santiago",
      "O'Higgins",
      "Maule",
      "Nuble",
      "Biobio",
      "La Araucania",
      "Los Rios",
      "Los Lagos",
      "Aysen",
      "Magallanes",
    ],
  },
  {
    country: "Colombia",
    prefix: "+57",
    departments: [
      "Amazonas",
      "Antioquia",
      "Arauca",
      "Atlantico",
      "Bolivar",
      "Boyaca",
      "Caldas",
      "Caqueta",
      "Casanare",
      "Cauca",
      "Cesar",
      "Choco",
      "Cordoba",
      "Cundinamarca",
      "Guainia",
      "Guaviare",
      "Huila",
      "La Guajira",
      "Magdalena",
      "Meta",
      "Narino",
      "Norte de Santander",
      "Putumayo",
      "Quindio",
      "Risaralda",
      "San Andres y Providencia",
      "Santander",
      "Sucre",
      "Tolima",
      "Valle del Cauca",
      "Vaupes",
      "Vichada",
      "Bogota D.C.",
    ],
  },
  {
    country: "Ecuador",
    prefix: "+593",
    departments: [
      "Azuay",
      "Bolivar",
      "Canar",
      "Carchi",
      "Chimborazo",
      "Cotopaxi",
      "El Oro",
      "Esmeraldas",
      "Galapagos",
      "Guayas",
      "Imbabura",
      "Loja",
      "Los Rios",
      "Manabi",
      "Morona Santiago",
      "Napo",
      "Orellana",
      "Pastaza",
      "Pichincha",
      "Santa Elena",
      "Santo Domingo de los Tsachilas",
      "Sucumbios",
      "Tungurahua",
      "Zamora Chinchipe",
    ],
  },
  {
    country: "Guyana",
    prefix: "+592",
    departments: [
      "Barima-Waini",
      "Pomeroon-Supenaam",
      "Essequibo Islands-West Demerara",
      "Demerara-Mahaica",
      "Mahaica-Berbice",
      "East Berbice-Corentyne",
      "Cuyuni-Mazaruni",
      "Potaro-Siparuni",
      "Upper Takutu-Upper Essequibo",
      "Upper Demerara-Berbice",
    ],
  },
  {
    country: "Paraguay",
    prefix: "+595",
    departments: [
      "Alto Paraguay",
      "Alto Parana",
      "Amambay",
      "Boqueron",
      "Caaguazu",
      "Caazapa",
      "Canindeyu",
      "Central",
      "Concepcion",
      "Cordillera",
      "Guaira",
      "Itapua",
      "Misiones",
      "Neembucu",
      "Paraguari",
      "Presidente Hayes",
      "San Pedro",
      "Asuncion",
    ],
  },
  {
    country: "Peru",
    prefix: "+51",
    departments: [
      "Amazonas",
      "Ancash",
      "Apurimac",
      "Arequipa",
      "Ayacucho",
      "Cajamarca",
      "Callao",
      "Cusco",
      "Huancavelica",
      "Huanuco",
      "Ica",
      "Junin",
      "La Libertad",
      "Lambayeque",
      "Lima",
      "Loreto",
      "Madre de Dios",
      "Moquegua",
      "Pasco",
      "Piura",
      "Puno",
      "San Martin",
      "Tacna",
      "Tumbes",
      "Ucayali",
    ],
  },
  {
    country: "Surinam",
    prefix: "+597",
    departments: ["Brokopondo", "Commewijne", "Coronie", "Marowijne", "Nickerie", "Para", "Paramaribo", "Saramacca", "Sipaliwini", "Wanica"],
  },
  {
    country: "Uruguay",
    prefix: "+598",
    departments: [
      "Artigas",
      "Canelones",
      "Cerro Largo",
      "Colonia",
      "Durazno",
      "Flores",
      "Florida",
      "Lavalleja",
      "Maldonado",
      "Montevideo",
      "Paysandu",
      "Rio Negro",
      "Rivera",
      "Rocha",
      "Salto",
      "San Jose",
      "Soriano",
      "Tacuarembo",
      "Treinta y Tres",
    ],
  },
  {
    country: "Venezuela",
    prefix: "+58",
    departments: [
      "Amazonas",
      "Anzoategui",
      "Apure",
      "Aragua",
      "Barinas",
      "Bolivar",
      "Carabobo",
      "Cojedes",
      "Delta Amacuro",
      "Distrito Capital",
      "Falcon",
      "Guarico",
      "Lara",
      "Merida",
      "Miranda",
      "Monagas",
      "Nueva Esparta",
      "Portuguesa",
      "Sucre",
      "Tachira",
      "Trujillo",
      "Vargas",
      "Yaracuy",
      "Zulia",
    ],
  },
];

export const DEFAULT_COUNTRY_PHONE = COUNTRY_PHONE_OPTIONS.find((option) => option.country === "Bolivia") ?? COUNTRY_PHONE_OPTIONS[0];

export function getPhonePrefixByCountry(country: string): string {
  return COUNTRY_PHONE_OPTIONS.find((option) => option.country === country)?.prefix ?? "";
}

export function getDepartmentsByCountry(country: string): string[] {
  return COUNTRY_PHONE_OPTIONS.find((option) => option.country === country)?.departments ?? [];
}

export function normalizeDepartmentByCountry(country: string, department?: string | null): string {
  const cleanDepartment = department?.trim() ?? "";
  if (!cleanDepartment) return "";

  return getDepartmentsByCountry(country).find(
    (option) => option.toLowerCase() === cleanDepartment.toLowerCase()
  ) ?? cleanDepartment;
}

export function formatPhoneWithPrefix(prefix?: string | null, phone?: string | null): string {
  const cleanPhone = phone?.trim() ?? "";
  const cleanPrefix = prefix?.trim() ?? "";

  if (!cleanPhone) return "";
  return [cleanPrefix, cleanPhone].filter(Boolean).join(" ");
}
